### ISSUE TITLE
clicking course from search result doesn't work

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/codingblocks.online.projectx#107]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/1327050/41196448-0bfcb204-6c5e-11e8-930e-78920ccc243b.png">

tested on both chrome and firefox

**Comment by abhishek97** [comment]
@championswimmer works for me. Can you make sure you don't have any console errors?

**Comment by architkshk** [comment]
Works for me.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/5001704/41198446-ffea4256-6c99-11e8-8d80-9df1cd62287b.gif)
