### ISSUE TITLE
fix overflow in doubts section 

### ISSUE THREAD

**Issue by witty123** [coding-blocks/codingblocks.online.projectx#109]
<img width="1440" alt="screen shot 2018-06-11 at 5 37 45 pm" src="https://user-images.githubusercontent.com/7976098/41230715-7891bfae-6d9e-11e8-8517-20e5eceb1f2c.png">

Make the required changes in motley repo

@architkshk Can you work on this since you have a fair idea of how to contribute in motley ?

**Comment by architkshk** [comment]
@witty123 created PR in motley https://github.com/coding-blocks/motley/pull/176
Please review.

**Comment by architkshk** [comment]
@witty123 Please close this issue.

**Comment by witty123** [comment]
You have to create one final PR in this repo for reflecting the changes done in motley

**Comment by architkshk** [comment]
@witty123 Done!!
