### ISSUE TITLE
Nav bar breaks on mobile

### ISSUE THREAD

**Issue by witty123** [coding-blocks/codingblocks.online.projectx#115]
Add user image as well
<img width="377" alt="screen shot 2018-06-13 at 5 20 31 pm" src="https://user-images.githubusercontent.com/7976098/41349634-1e18180c-6f2e-11e8-863f-a765628f82be.png">

**Comment by firefinchdev** [comment]
I am working on this issue.

**Comment by architkshk** [comment]
@witty123 I don't understand this issue. Please explain.
![screenshot from 2018-06-13 13-25-19](https://user-images.githubusercontent.com/5001704/41337620-5a83c4f6-6f0d-11e8-9580-0e0a388abd1d.png)

**Comment by VibhorCodecianGupta** [comment]
Done, #116

**Comment by firefinchdev** [comment]
Done #113

**Comment by witty123** [comment]
@architkshk open the navbar in mobile (hamburger)

**Comment by firefinchdev** [comment]
![screenshot from 2018-06-13 17-20-15](https://user-images.githubusercontent.com/26357501/41349670-3ada14a4-6f2e-11e8-9db0-f9254fe5ff4e.png)
