### ISSUE TITLE
Add content icons in course content page

### ISSUE THREAD

**Issue by witty123** [coding-blocks/codingblocks.online.projectx#122]
![whatsapp image 2018-06-14 at 00 53 25](https://user-images.githubusercontent.com/7976098/41397746-cb922122-6fd2-11e8-9168-be708f774aac.jpeg)

**Comment by venomousboxer** [comment]
@witty123 can you plss share the icons to be used

**Comment by witty123** [comment]
https://github.com/coding-blocks/codingblocks.online.projectx/tree/master/public/images

You can take help from this file https://github.com/coding-blocks/codingblocks.online.projectx/blob/master/app/pods/classroom/timeline/contents/template.hbs
