### ISSUE TITLE
Design and Implement Search on contents

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#131]
On the Course consumption screen, it will be handy to be able to search on content names. 

- [x] Design and layout of the search UI (Bounty: 200)
- [ ] Implementation for Design (CSS, to done via motley) (Bounty: 500)
- [ ] Feature Implementation (Ember) (Bounty: 1000)

Note: No need to make separate API calls to get search results, assume all data to be loaded on the frontend only.

This is the course consumption screen:

![screen shot 2018-06-19 at 8 12 04 pm](https://user-images.githubusercontent.com/8109774/41604883-e25292aa-73fd-11e8-98e6-c1d05f21569c.png)

**Comment by architkshk** [comment]
@abhishek97 These are my proposed design - 
![concept1-destop](https://user-images.githubusercontent.com/5001704/41614646-a4a030f2-7416-11e8-943f-19f43d470f87.png)
![concept1-mob](https://user-images.githubusercontent.com/5001704/41614650-a51c0132-7416-11e8-916a-34d7801cfcdd.png)

**Comment by abhishek97** [comment]
@sidjain2901 ^ thoughts on the UI?

**Comment by sidjain2901** [comment]
@architkshk The UI looks fine. Just try changing the search icon though, it looks streched. You can take reference from flaticon.com

**Comment by abhishek97** [comment]
Okay, so we are using @architkshk 's design on this.

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 #230

**Comment by architkshk** [comment]
@abhishek97 already done https://github.com/coding-blocks/codingblocks.online.projectx/pull/236 earlier

**Comment by firefinchdev** [comment]
@abhishek97 Done Completely #237 
Pls Review.

**Comment by abhishek97** [comment]
Since this issue can be closed now. Here is how i plan to divide the final bounties

- Design and layout of the search UI (Bounty: 200) @architkshk 
- Implementation for Design (CSS, to done via motley) (Bounty: 500) (50/50 split) 
    - 250 Bounty @architkshk for initial work
    - 250 Bounty @firefinchdev  
- Feature Implementation (Ember) (Bounty: 1000) @firefinchdev 

Please make claims accordingly.
