### ISSUE TITLE
Make Notification Box Close when clicked outside it

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#132]
![screen shot 2018-06-20 at 1 35 54 pm](https://user-images.githubusercontent.com/8109774/41645512-da19bb72-748e-11e8-8eb6-fc4a48b5eb7a.png)

Currently only way to close it is clicked the bell icon again.

**Comment by Rishabh570** [comment]
@abhishek97 I would like to work on it...
