### ISSUE TITLE
show modal with video player instructions

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/codingblocks.online.projectx#136]
Show a modal with following info when user plays a self-hosted video (not during Youtube ones)

- up/down changes video speed
- left right seeks +/- 5 sec in video

Add a checkbox with "Do not show again" option, which if ticked, will not show again. 
Save the "do not show again" boolean in user's localstorage.

**Comment by VibhorCodecianGupta** [comment]
Done #226 @witty123 @abhishek97

**Comment by firefinchdev** [comment]
@championswimmer 
Pls close this. It has been solved.
