### ISSUE TITLE
Show Appropriate message in case there are no contents in the course

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#142]
On the course timeline page, show the following message if there are no contents.

![screen shot 2018-06-22 at 11 24 54 pm](https://user-images.githubusercontent.com/8109774/41791553-a29da1ea-7673-11e8-9595-712cae8cf575.png)

**Comment by Dhroov7** [comment]
@abhishek97 Done! PR #148

**Comment by Dhroov7** [comment]
@abhishek97 Done with changes.
