### ISSUE TITLE
Docs are needed to ease the process of getting started with the project.

### ISSUE THREAD

**Issue by Rishabh570** [coding-blocks/codingblocks.online.projectx#175]
Currently, it's hard for a beginner to set-up everything correctly and gets going with the project and clearly, docs are the best solution for it.

Like currently, after getting auth code in the URL, it's very hard for a new timer to know the next step, which results in a lot of confusion and time-waste. (experiencing it!)

**Comment by VibhorCodecianGupta** [comment]
Were you able to resolve this @Rishabh570 ? You could post how you set up everything here, for future reference to contributors :D

**Comment by Rishabh570** [comment]
@VibhorCodecianGupta Unfortunately Nope, I still don't know what to do next :xD

**Comment by VibhorCodecianGupta** [comment]
@abhishek97

**Comment by abhishek97** [comment]
@Rishabh570 @VibhorCodecianGupta @architkshk 
I have updated the readme with instruction on running this project(commit 3f2519037bac96df6bf189c9ce74e59c9e8e0f89 and bab3555122bfc2e45e56c2385f30643e1cabeb98 ). I've hosted an instance of our backend with very limited database to get the application running. Keep in mind the backend instance is running on free-tier heroku, so load times will be slow. Update here, if you face any issues.

**Comment by Rishabh570** [comment]
@abhishek97 I agree with @VibhorCodecianGupta 😄

**Comment by abhishek97** [comment]
It is already there. Please see both the runs.

**Comment by abhishek97** [comment]
I'm closing this issue. Feel free to re-open or create another issue if you have any problems/questions.

**Comment by Rishabh570** [comment]
@abhishek97 Sorry, but I couldn't find any content on both the runs. Please correct me if I'm wrong :confused:
