### ISSUE TITLE
Show if Run is premium or not on "My Courses" page.

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#177]
Use suitable styling.

<img width="489" alt="screen_shot_2018-07-02_at_5_22_47_pm" src="https://user-images.githubusercontent.com/8109774/42162989-737d239c-7e1e-11e8-8d29-92cf7a8353a0.png">

**Comment by Dhroov7** [comment]
@abhishek97 Done PR #180
