### ISSUE TITLE
Update Title of page 

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#178]
Change the page `<title></title>` to the following when viewing content.

`<section name> : <content name>`

Possible ways of implmenting:

- Implement a new `title` service, it will appropriate methods to set/get title, section, content name etc..
- You will need to Jquery to update the title, since it is outside ember app.

- Or you can use the addon: http://tim-evans.github.io/ember-page-title/

EDIT: Also update title suitably for all the pages.

**Comment by architkshk** [comment]
@abhishek97 How do I test the application?

**Comment by firefinchdev** [comment]
Done @abhishek97 #181

**Comment by abhishek97** [comment]
Closed in #181
