### ISSUE TITLE
[SEO] change page title of homepage to `Coding Blocks: Online Courses` 

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/codingblocks.online.projectx#183]
Note: The html `<title>` not anything to do with UI

**Comment by championswimmer** [comment]
Also change the `alt` of the top left logo to  - **Coding Blocks Online**

**Comment by VibhorCodecianGupta** [comment]
@championswimmer  Done, #184

**Comment by abhishek97** [comment]
@championswimmer The title change issue is already here https://github.com/coding-blocks/codingblocks.online.projectx/issues/178

**Comment by witty123** [comment]
@VibhorCodecianGupta relatively smaller change so reduced the bounty points :) Hope you understand
closed in #184
