### ISSUE TITLE
Only allow ratings by users enrolled in "premium: true" run

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#188]
You can use "premium" property on "runAttempt" record.

**Comment by VibhorCodecianGupta** [comment]
Isn't this resolved in [49498b4](https://github.com/coding-blocks/codingblocks.online.projectx/commit/49498b4cb9f8359d75f159f1530a8f6e36aab005)?

**Comment by abhishek97** [comment]
Yes
