### ISSUE TITLE
Render Announcements as markdown

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#199]
Example: http://localhost:4200/classroom/course/26/run/31/announcements

<img width="702" alt="screen shot 2018-07-09 at 4 52 22 pm" src="https://user-images.githubusercontent.com/8109774/42447750-8825b992-8398-11e8-932c-ec86c848ddbd.png">

**Comment by VibhorCodecianGupta** [comment]
#200 @abhishek97

**Comment by pg07codes** [comment]
If this has been fixed, please close the issue.
