### ISSUE TITLE
non valid requests should redirect to home

### ISSUE THREAD

**Issue by pg07codes** [coding-blocks/codingblocks.online.projectx#201]
![image](https://user-images.githubusercontent.com/34238240/42510007-3eb8b09c-846b-11e8-99dc-affd6b290e7e.png)

request to any non valid url should redirect back to the home page and not just show up blank like it does now.

**Comment by abhishek97** [comment]
A 404 page would be apter, let have that.

**Comment by VibhorCodecianGupta** [comment]
Done, #203
