### ISSUE TITLE
singularize batches -> batch if no is 1

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/codingblocks.online.projectx#21]

**Comment by shreyateeza** [comment]
@championswimmer Please elaborate on this issue. I find it difficult to understand.

**Comment by architkshk** [comment]
Please tell where we have to change this. In a course's about section?

**Comment by ananay** [comment]
Fixed!
@championswimmer 
https://github.com/coding-blocks/codingblocks.online.projectx/pull/65

**Comment by ananay** [comment]
Here's a separate PR for this issue. Please merge this. https://github.com/coding-blocks/codingblocks.online.projectx/pull/69

**Comment by championswimmer** [comment]
Not valid anymore after the card ui changes
