### ISSUE TITLE
Limit height of course's summary 

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#218]
Limit the height of the summary here, also add a `Read more` link to expand to full the summary. While you are at it, parse it as markdown.

<img width="753" alt="screen shot 2018-07-24 at 12 47 52 pm" src="https://user-images.githubusercontent.com/8109774/43122803-e3970332-8f3f-11e8-9174-56e7767f7813.png">

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 I am not able to see any course run contents. The page isn't loading in the first page. Been this way for quite a while, a little help?

**Comment by abhishek97** [comment]
@VibhorCodecianGupta Do you see any errors or see no content?. You can enroll in trial version of the course and see the content there.
