### ISSUE TITLE
Remove otp enroll option and add free trial instead

### ISSUE THREAD

**Issue by witty123** [coding-blocks/codingblocks.online.projectx#238]
<img width="393" alt="screen shot 2018-08-11 at 5 11 05 pm" src="https://user-images.githubusercontent.com/7976098/43991427-440b50b2-9d8a-11e8-8a35-837aac920123.png">
<img width="1439" alt="screen shot 2018-08-11 at 5 11 12 pm" src="https://user-images.githubusercontent.com/7976098/43991429-46bebe98-9d8a-11e8-8322-fe8f3feb4eaf.png">
Replace otp enroll with free trial, get currently running batch and add href for run attempt of that batch.

**Comment by Dhroov7** [comment]
@witty123 Please review. #241
