### ISSUE TITLE
Highlight the current content

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#245]
The content which is currently being viewed should be highlighted in some manner to provide feedback to the user. 

- The Design and DOM layout (motley PR): 300 Bounty
- Implementation: 200 Bounty

<img width="588" alt="screen_shot_2018-08-12_at_9_52_18_pm" src="https://user-images.githubusercontent.com/8109774/44004094-335160ae-9e7a-11e8-9d4e-39c35fbeb5ae.png">

**Comment by firefinchdev** [comment]
![screenshot from 2018-08-12 22-26-51](https://user-images.githubusercontent.com/26357501/44004352-fba12374-9e7e-11e8-817e-f20226c27fde.png)
@abhishek97 
This looks perfect. Pls Review.

**Comment by firefinchdev** [comment]
![screenshot from 2018-08-12 22-30-24](https://user-images.githubusercontent.com/26357501/44004368-5a9a33de-9e7f-11e8-8db9-d0ebb5c1998f.png)
Or this also (difference in brightness)

**Comment by firefinchdev** [comment]
![screenshot from 2018-08-12 22-35-45](https://user-images.githubusercontent.com/26357501/44004424-2a69dfd8-9e80-11e8-8149-43510931c04b.png)

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 

**Proposed design:**

![screen shot 2018-08-12 at 10 38 23 pm](https://user-images.githubusercontent.com/29275810/44004448-82170c2e-9e80-11e8-80c2-0a85bccc8640.png)

**Comment by architkshk** [comment]
@abhishek97 
![screenshot from 2018-08-12 22-43-37](https://user-images.githubusercontent.com/5001704/44004523-5118e1b4-9e81-11e8-9c39-781b015b5d57.png)
https://github.com/coding-blocks/motley/pull/257

**Comment by firefinchdev** [comment]
![screenshot from 2018-08-12 22-56-29](https://user-images.githubusercontent.com/26357501/44004640-06343264-9e83-11e8-928e-3a4aa6034a2a.png)
Another design

**Comment by firefinchdev** [comment]
https://github.com/coding-blocks/motley/pull/259
https://github.com/coding-blocks/motley/pull/260
https://github.com/coding-blocks/motley/pull/261
https://github.com/coding-blocks/motley/pull/262
@abhishek97 These are my proposed designs.
Pls Review.

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 #257 done. First commit. Please review :)

**Comment by witty123** [comment]
Previous PRs on online projectx had issues. #250 and #257 
Use {{link-to}} for managing the state instead of adding and removing classes.
Please submit new PRs.

**Comment by VibhorCodecianGupta** [comment]
@witty123 @abhishek97 please have a look at  coding-blocks/motley#267 (accepted design and DOM implementation). I need help to make a claim on these.
