### ISSUE TITLE
visited link color has no contrast with button

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/codingblocks.online.projectx#25]
<img width="146" alt="image" src="https://user-images.githubusercontent.com/1327050/39962249-9cc49fc6-5666-11e8-85a1-51cb87765025.png">

**Comment by AshishkrGoyal** [comment]
@championswimmer i am working for this issue and will send pr as soon as possible 
Thanks

**Comment by ananay** [comment]
![image](https://user-images.githubusercontent.com/5569219/40028404-43da4054-57fc-11e8-8419-446ebf8556c6.png)

Already seems to be fixed here

**Comment by abhishek97** [comment]
This was fixed by the dev team.
