### ISSUE TITLE
Feedback integration

### ISSUE THREAD

**Issue by witty123** [coding-blocks/codingblocks.online.projectx#251]
Implement feedback modal on course dashboard page. 
Designs here : https://github.com/coding-blocks/motley/pull/255

**Comment by firefinchdev** [comment]
Done #252

**Comment by VibhorCodecianGupta** [comment]
@witty123 #254, done earlier

**Comment by VibhorCodecianGupta** [comment]
@witty123 refactored, please have a look #254
