### ISSUE TITLE
Add jivochat for mobile only

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#259]
Need to add this script to DOM based on User Agent String - for Mobile Only

```
<script type="text/javascript" async="" src="//code.jivosite.com/script/widget/ASYGLZQ6UC"></script>
```

To be clear -> Need to add this script to the DOM. So that it loads jivo chat on mobile.

**Comment by VibhorCodecianGupta** [comment]
#261 done
first commit. @abhishek97 please review

**Comment by abhishek97** [comment]
Guys, 
I know that this is a competition. However, please have courtesy. 
1. Only open up a PR if you have something to add/improve to an already existing PR, If you do have something please mention it. Don't just redo work, it's a waste.
2. None of the proposed PRs actually do what is required here. Anyone mind explaining what `document.write` do? or did others just copy it? Why would it solve the purpose here?

BOSS is a competition. however, it is also aimed at making people aware of Open Source development and giving them a chance to contribute and work together on projects while learning new things along the way. Please keep that in mind.

**Comment by championswimmer** [comment]
@VibhorCodecianGupta @architkshk @firefinchdev 
One change - 

here is the actual code snippet to be used

```html
<!-- BEGIN JIVOSITE CODE {literal} -->
<script type='text/javascript'>
(function(){ var widget_id = 'ASYGLZQ6UC';var d=document;var w=window;function l(){
var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);}if(d.readyState=='complete'){l();}else{if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();</script>
<!-- {/literal} END JIVOSITE CODE -->
```

Only this 
```
<script type="text/javascript" async="" src="//code.jivosite.com/script/widget/mm3xh9v8wk"></script>
```
will not work for all cases

**Comment by firefinchdev** [comment]
@championswimmer Updated #262 
Pls Review.

**Comment by architkshk** [comment]
@championswimmer pls also review #260

**Comment by VibhorCodecianGupta** [comment]
@championswimmer @witty123 #265
