### ISSUE TITLE
if price == 0, show "free" instead of Rs. 0

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/codingblocks.online.projectx#27]
<img width="143" alt="image" src="https://user-images.githubusercontent.com/1327050/39962282-81d3798e-5667-11e8-94ae-283d21300340.png">

**Comment by v27u27** [comment]
i am working on this

**Comment by abhishek97** [comment]
@v27u27 Yes you can. We already do have ember truth helpers as a dependency for this project, feel free to use them. However, it might not be the best for this case.

**Comment by v27u27** [comment]
@abhishek97  any suggestion, like what would be the ideal way of handling it?

**Comment by abhishek97** [comment]
Write your own helper to evaluate a string either `INR <amount>` or `Free`.

Then use it like {{formatPrice run.price}}
