### ISSUE TITLE
Replace recommended-courses loader with skeleton cards

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#29]
It will be nice to have a skeleton behavior while loading.

![screen shot 2018-05-13 at 4 58 19 pm](https://user-images.githubusercontent.com/8109774/39966764-d41579ba-56ce-11e8-815d-2fb0596dab29.png)

The required asset: https://www.dropbox.com/s/kmhfsrjgiamgswq/blankcard.svg?dl=0

BOSS: Bonus 100 Bounty points for animating it via CSS.

**Comment by shreyateeza** [comment]
I am working on this issue.

**Comment by hereisnaman** [comment]
@abhishek97 these are the PRs
ProjectX: https://github.com/coding-blocks/codingblocks.online.projectx/pull/66/
Motley: https://github.com/coding-blocks/motley/pull/138

**Comment by witty123** [comment]
Bumping up the bounty points for more recognition.

**Comment by VibhorCodecianGupta** [comment]
Done @witty123 @abhishek97 #228

**Comment by witty123** [comment]
Bumped up bounty points for additional work done.
