### ISSUE TITLE
http to https redirection

### ISSUE THREAD

**Issue by pg07codes** [coding-blocks/codingblocks.online.projectx#295]
I think it will be much better to redirect user from http to https like its done on codingblocks.com site and so such errors will also go away.
![capture](https://user-images.githubusercontent.com/34238240/48300979-4b454800-e50c-11e8-9c41-b67cf99f0cc2.PNG)

**Comment by championswimmer** [comment]
@pg07codes good catch

@abhishek97 I think we can enable this in Netlify settings ?

**Comment by abhishek97** [comment]
We no longer use Netlify for production here. I'll take care of this.
