### ISSUE TITLE
Search input not responsive

### ISSUE THREAD

**Issue by hereisnaman** [coding-blocks/codingblocks.online.projectx#35]
The search input box have static 375px width, which cause overflow on mobile screens. SS: 
![screen shot 2018-05-14 at 10 59 11 pm](https://user-images.githubusercontent.com/22571395/40013224-9a71d76a-57ca-11e8-8822-fcc8f33c32fa.png)

**Comment by hereisnaman** [comment]
resolved: https://github.com/coding-blocks/codingblocks.online.projectx/pull/36

**Comment by abhishek97** [comment]
This issue no longer applies.
