### ISSUE TITLE
Show spinner while loading more courses

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#350]
https://online.codingblocks.com/courses

When user clicks "Load More" button, a spinner should indicate loading state

**Comment by DevanandGowda** [comment]
@abhishek97 Can you assign this to me. It would be helpful for me to get started contributing
 to CodingBlocks since its a good first issue.

**Comment by abhishek97** [comment]
Yes, you can start working on this. However we don't assign issues for BOSS.

**Comment by nileshpatra** [comment]
@abhishek97 , I added a PR , please review .

**Comment by sachin235** [comment]
@abhishek97 @championswimmer 
Please review my PR #411 for this issue

**Comment by nileshpatra** [comment]
@championswimmer , added #412 , rectified changes asked in #408

**Comment by rakshitkumarcse** [comment]
@abhishek97 @championswimmer  I fixed this issue using #407 
However, I did not get the bounty, and my username is not shown on the leaderboard. Can you please help?
