### ISSUE TITLE
Fix course card's loading state

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#399]
The course cards are much smaller now, but we use the same shadow skeleton as before(when we had bigger cards). 
Need to change these loading cards accordingly.

Maybe use: https://github.com/DavyJonesLocker/ember-skeleton

**Comment by Manit1** [comment]
Hey @abhishek97,
Currently, I can see the application uses markup to show the skeleton so should it be replaced with an entire image or gif? or do we need to include images in the current markup (like placeholder images for the mentors and course logo)?

**Comment by abhishek97** [comment]
This issue was already closed.
