### ISSUE TITLE
New lecture video would not play automatically

### ISSUE THREAD

**Issue by iamspathan** [coding-blocks/codingblocks.online.projectx#409]
When a lecture ends next lecture will start but video not play automatically, we have refresh the window

**Comment by abhishek97** [comment]
It brings you to next video, you have to click on play. 
I don't get what you mean by "we have refresh the window"

**Comment by iamspathan** [comment]
Actually what happens at that time was next lecture came but old video is still in that  lecture😐 , I was thinking that it happens because of internet

**Comment by iamspathan** [comment]
I think video should automatically play.

**Comment by abhishek97** [comment]
@iamspathan I'm not sure what you are reoffering to here. Maybe some screenshots will help. 

> "next lecture came but old video is still in that lecture"

 What does mean?
