### ISSUE TITLE
Create sections in my courses

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/codingblocks.online.projectx#427]
Create 3 sections in My Courses
1. Current Courses
2. Free Trials
3. Expired Courses

Populate the sections accordingly.

**Comment by farhan787** [comment]
@jatinkatyal13 I'm working on this.

**Comment by farhan787** [comment]
@jatinkatyal13 while I'm logging into my account via GitHub token, this url `http://localhost:4200/?code=myGitHubAccessToken` keeps on loading as long as I'm letting it to load.

**Comment by promaroy** [comment]
Can I work on this issue??
