### ISSUE TITLE
Background not configured properly

### ISSUE THREAD

**Issue by crusader2000** [coding-blocks/codingblocks.online.projectx#448]
#63

![Screenshot from 2019-07-16 20-04-01](https://user-images.githubusercontent.com/43775333/61303478-32acd080-a805-11e9-84c7-82040a1ad3bb.png)

The background does not cover the section properly

**Comment by jatinkatyal13** [comment]
According to the designs it is meant to be that way ! Although you can work on some CSS fixes on our Motley project 😄
