### ISSUE TITLE
Background of logout is not proper.

### ISSUE THREAD

**Issue by samagragupta** [coding-blocks/codingblocks.online.projectx#450]
### Is this issue regarding CSS? 
This project uses motley(https://github.com/coding-blocks/motley/) as CSS framework, consider opening an issue there instead.
![Capture](https://user-images.githubusercontent.com/32234926/61574991-fd91ce00-aae3-11e9-9b39-e67eb0efbc21.JPG)

**Comment by samagragupta** [comment]
@championswimmer Please add BOSS

**Comment by radharaniraj** [comment]
is this issue still open,can i work on this issue??
