### ISSUE TITLE
Social media links are opening in the current tab

### ISSUE THREAD

**Issue by leelatanniru** [coding-blocks/codingblocks.online.projectx#472]
Steps to reproduce :
1. Open https://online.codingblocks.com/app/
2. Scroll down to footer section.
3. Click on any social media links (facebook, twitter, youtube, github, linkedIn)
4. Links are opening in the current tab.

Expected:
Links should be open in a new tab so that the user can have better experience.

**Comment by hv-ojha** [comment]
I think this issue is closed so can you please mark this as closed..
