### ISSUE TITLE
Terms & Conditions and Privacy Policy are opening in the current tab.

### ISSUE THREAD

**Issue by leelatanniru** [coding-blocks/codingblocks.online.projectx#474]
Steps to reproduce :
1. Open https://online.codingblocks.com/app/
2. Scroll down to footer section.
3. Click on any Terms & Conditions
4. Link is opening in the current tab.
Same issue for Privacy Policy button.

Expected:
Links should be open in a new tab so that the user can have better experience.

**Comment by prateekpardeshi** [comment]
@leelatanniru Mark this issue as closed
