### ISSUE TITLE
CB image link not redirecting to home page

### ISSUE THREAD

**Issue by till-tomorrow** [coding-blocks/codingblocks.online.projectx#50]
![logincb](https://user-images.githubusercontent.com/21954525/40045011-c47a3fbc-5846-11e8-9407-412919ffe486.JPG)

The icon on the top of the page is not redirecting the page to the home page
"https://online.codingblocks.com", but is more like a refresh button for 
the login page!!

**Comment by abhishek97** [comment]
We use `account.codingblocks.com` (oneauth) as SSO provider. So when you click login on any of codingblocks products it redirects to `account.codingblocks.com` which is a website of its own. Similar to when you click login on youtube, it redirects to accounts.google.com.
