### ISSUE TITLE
Shepherd.js usage

### ISSUE THREAD

**Issue by rwwagner90** [coding-blocks/codingblocks.online.projectx#511]
Hi! I noticed you guys are using Shepherd and ember-shepherd. We would love to showcase you as a user, if you are up for it!

**Comment by abhishek97** [comment]
Yes we will be delighted. 👍

**Comment by rwwagner90** [comment]
@abhishek97 awesome! What's a good way to get in touch? Email, discord, etc?

**Comment by abhishek97** [comment]
Over email: abhishek.gupta@codingblocks.com
