### ISSUE TITLE
Need to Update the and Remove the Button "Login with OTP" on My Course Section

### ISSUE THREAD

**Issue by codewithdev** [coding-blocks/codingblocks.online.projectx#558]
If the User is already logged in No need to show "Login with OTP". 
Update Needed to change the Button to "Enroll Now"
![Capture](https://user-images.githubusercontent.com/44609609/82091904-de6cc880-9715-11ea-8fdf-ef808a605399.JPG)

**Comment by abhishek97** [comment]
Enroll to OTP features is meant to be used users who have been granted access to a course but don't have codingblocks account yet. It isn't for login.
