### ISSUE TITLE
The mobile nav-bar should close when clicking on any nav-link

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#56]
![screen shot 2018-05-16 at 1 14 39 pm](https://user-images.githubusercontent.com/8109774/40103486-35495ea2-590b-11e8-9a39-38ee985c3578.png)

**Comment by architkshk** [comment]
please check #57

**Comment by architkshk** [comment]
Please add a bounty to this issue.

**Comment by architkshk** [comment]
@abhishek97 Is this issue not covered under BOSS?

**Comment by abhishek97** [comment]
@architkshk You can claim this now, forgot to add the bounty.

**Comment by architkshk** [comment]
Thank you
