### ISSUE TITLE
Redirect to login when Otp-enroll button on courses/:id is clicked

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#62]
Currently, for loggedIn users `Enroll via OTP` buttons on `courses/:id` pages redirect to `/classroom`. 

If the user is unauthenticated, We need to make the user go through the login flow (similar to what happens when the user clicks `login`)

Make sure to cover both the login buttons.

**Comment by ananay** [comment]
Done! https://github.com/coding-blocks/codingblocks.online.projectx/pull/65

**Comment by ananay** [comment]
https://github.com/coding-blocks/codingblocks.online.projectx/pull/68

**Comment by ananay** [comment]
@abhishek97 please close
