### ISSUE TITLE
There is issue in https://hack.codingblocks.com/app/contests/1903 .

### ISSUE THREAD

**Issue by AdityaTeltia** [coding-blocks/codingblocks.online.projectx#620]
!How to Reproduce error ?
https://hack.codingblocks.com/app/contests/1903
the screen is shifting left right in hackerblocks 
This is happening for window width 1010 px 
It is switching from 1010px and 1027px continuously 
@championswimmer please check this is really annoying .

**Comment by championswimmer** [comment]
cc: @jatinkatyal13

**Comment by jatinkatyal13** [comment]
Hey @AdityaTeltia 

Thanks for the report 👍 . 

Can you please also add a GIF/Video of the same? 

If not a video it'll be a great help if you can answer the following:
1. Does the shifting happen when you try to scroll or hover on the scroll bar?
2. Is the left SideBar (the black navigation strip) stretched from top to bottom?
3. When you said it is switching from 1010px to 1027px do you mean the sudden change in the width of the container?
4. Have you zoomed in or zoomed out the webpage?

Thanks again for helping us build a better product.

**Comment by AdityaTeltia** [comment]
Answers:
No , irrespective of any hover it is happening continuously .
It happens all the time for my screen resolution irrespective of I do anything
The change is sudden but its keep on switching and scrollbar appears and go away.
I have not zoomed in or zoomed out its the resolution of my screen where it is happening
![Hackerblocks - Google Chrome 10_8_2020 11_53_58 PM](https://user-images.githubusercontent.com/67232537/95499334-c4809a80-09c2-11eb-8df5-6c5185d7f5fa.gif)
I am doing web development can i try resolving this issue , will tell you whether i was able to resolve it or not.

**Comment by jatinkatyal13** [comment]
@AdityaTeltia that'll be amazing, you can surely try solving the issue at https://github.com/coding-blocks/hackerblocks.projectx

**Comment by AdityaTeltia** [comment]
I can think of one way by changing media query width from 991 px to 1080 px , I have tried this and this resolves the issue .
Moreover , I was thinking of changing the scrollbar css just like in the picture as it goes good with the website theme .
![scrooo](https://user-images.githubusercontent.com/67232537/95502526-95b8f300-09c7-11eb-8761-0ac7a769f93f.JPG)
