### ISSUE TITLE
Remove `code` queryParam when user is loggedIn

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online.projectx#73]
remove the `code` query param in URL when the user is loggedIn.

![screen shot 2018-05-23 at 4 13 39 pm](https://user-images.githubusercontent.com/8109774/40419908-4f6367a8-5ea4-11e8-863d-e391e9f9b648.png)

**Comment by VibhorCodecianGupta** [comment]
#85 is the concerned pull request for this issue. Please review :)

**Comment by abhishek97** [comment]
Fixed in #85
