### ISSUE TITLE
use svg for course content icons

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/codingblocks.online.projectx#90]
![image](https://user-images.githubusercontent.com/1327050/40848449-e71f03f6-65dc-11e8-84e1-f595cfe59ac1.png)

This is 500 points because whoever solves the issues needs to come up with the svgs too :D 
(Use a PNG as a fallback probably)

**Comment by ananay** [comment]
On it!

**Comment by VibhorCodecianGupta** [comment]
Done in #97! Please review :)

**Comment by VibhorCodecianGupta** [comment]
Done in #98! Please review :)

**Comment by ananay** [comment]
@championswimmer @abhishek97 Done!
https://github.com/coding-blocks/codingblocks.online.projectx/pull/101

**Comment by VibhorCodecianGupta** [comment]
Why was #174 closed? No reviews/suggestions? @witty123 @abhishek97 ?
